### ISSUE TITLE
resinOS & mbed-edge

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-edge#1]
Thoughts on using mbed-edge with [resinOS](https://resinos.io/docs/)?

**Comment by loverdeg-ep** [comment]
@jjaakola-arm

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTGW-536

**Comment by loverdeg-ep** [comment]
@JanneKiiskila Sounds about right. 

However I think the [embedded](https://resinos.io/docs/faqs/), [networking](https://resinos.io/docs/architecture/#docker), and [developer tools](https://resinos.io/docs/architecture/#os-tools) focus of resinOS would very much benefit mbed-edge.

Before knowing the details of edge I was sort of hoping it would be something similar to resinOS. 
As it turns out they may be complimentary and that is just as good.

**Comment by JanneKiiskila** [comment]
Seems resin OS uses pretty much Yocto as is, so can you just build Edge on top of ResinOS using the metalayers as is, what the benefit of having Edge within a container?

**Comment by loverdeg-ep** [comment]
@JanneKiiskila 
Just to play this out... my first pass based on the diagrams found in the [intro docs](https://cloud.mbed.com/docs/current/connecting/mbed-edge.html) was 

* each protocol translator in a container (may have issues accessing hardware)
* edgework applications in individual containers
* edge core in a container with update-partition mounted for... yeah no clue how to update containers individually or elegantly with cloud-client running in a container.
