### ISSUE TITLE
wrong branch name for repo Mbed TLS

### ISSUE THREAD

**Issue by vince-zeng** [ARMmbed/mbed-edge#11]
We have switched Mbed TLS to version  2.15.1, but in .gitmodules, the branch name is still mbedtls-2.4. It is confused and suggest to correct it. 

`
[submodule "lib/mbedtls"]
	path = lib/mbedtls
	url = https://github.com/ARMmbed/mbedtls
	branch = mbedtls-2.4
`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTGW-1041

**Comment by JanneKiiskila** [comment]
Hi @vince-zeng 

Good spot - this will be fixed for the next release. Process change also implemented to add it to our checklist, so that we do not forget it in the future.

**Comment by JanneKiiskila** [comment]
Seems `git init submodule` does not do anything with that information, we will drop the branch completely from there in our next release (0.10.0).

**Comment by ygoyal18** [comment]
Fixed in 0.11.0 release - https://github.com/ARMmbed/mbed-edge/blob/0.11.0/.gitmodules
