### ISSUE TITLE
Cmake failure with the latest version code

### ISSUE THREAD

**Issue by vince-zeng** [ARMmbed/mbed-edge#17]
Test environment: Ubuntu 16.04 
Test steps: follow up the instructions in readme. 

With the latest code tag 0.11.0, it will fail when run `cmake -DDEVELOPER_MODE=ON -DFIRMWARE_UPDATE=OFF ..` command. 

With tag 0.10.0 ,  I can complete the build successfully.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTGW-1068

**Comment by coisme** [comment]
I needed to run the command
```
$ git submodule update --init --recursive
```
instead of 
```
$ git submodule init
$ git submodule update
```
which is described in README.md. Readme should be updated.

**Comment by cmonr** [comment]
Simple enough fix. Fixed in https://github.com/ARMmbed/mbed-edge/pull/18

Opted to keep the commands separate to keep the change as minimal as possible, but running the singular command will work as well.

**Comment by ygoyal18** [comment]
Readme was updated. Marking this resolved and closing it.
