### ISSUE TITLE
Protocol translator API documentation - missing

### ISSUE THREAD

**Issue by JoelHGoodman** [ARMmbed/mbed-edge#2]
Where is the Protocol Translation API Documentation?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTGW-628

**Comment by jjaakola-arm** [comment]
The API docs are available here:
https://cloud.mbed.com/docs/current/mbed-edge-api/index.html

**Comment by JoelHGoodman** [comment]
There is nothing here, it's just a referral to the mbed cloud documentation.
And on the mbed cloud documentation, there is no explanations on how to actually use the protocol translation SDK in either place.

**Comment by jjaakola-arm** [comment]
I'll open this back and start discussion on the documentation Everything is currently in Mbed Cloud documentation and I agree that it is disconnected from this repo.

@JoelHGoodman please chip in if you have further feedback.

**Comment by JoelHGoodman** [comment]
Please add ran shenhar to thread

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iriark01** [comment]
We have three issues here:

1. The documentation doesn't explain how to use the SDK. That is a bug we'll need to fix. Please consider dropping a task on our Jira queue.

2. The readme in this repo doesn't direct people to the docs site or to a mechanism for docs feedback, so it's a "dead end". That is a bug we can fix very easily; I'll open a PR against the readme in a few minutes.

3. The documentation isn't with the code. This is currently the standard procedure for ISG docs (Mbed OS docs aren't with the code, either). There is room for an internal discussion about this, but a transition will not be easy for the Docs Team for several reasons. I'll list four major ones:
    a. Docs that work on the docs site won't look great on GitHub, so we don't want people to read the docs on GitHub. Therefore our motivation for co-locating the docs and code is a bit low.
    b. An engineering team has to think of just one or two of its own repos on top of the single docs repo. The Docs Team will have to contend with a couple of dozen engineering repos. That is an overhead we're not able to deal with at our current size (and we don't have a PjM to help with coordinating that). As proof that this is difficult, just look at the swagger repo; we've had multiple misses with it. So it's not an unsolvable problem, but probably one we're better off not tackling until the team is bigger. 
    c. The engine we use to publish the docs is currently being reworked to allow generating local builds of PRs and other ad-hoc branches to help speed up reviews. In the future this enhancement might be able to work on all repos, but the first phase will limit it to the docs repos. 
    d. We will have to be given push access to code repos; that's a bit dangerous. The alternative, approving our PRs, will bring engineering teams to their knees - we churn through commits.

**Comment by JoelHGoodman** [comment]
Looping Ran in

Joel Goodman | Field Application Engineer – IoT & Mbed Cloud | Arm
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Mobile: +1 (312) 581-8929
Skype: joel.goodman@arm.com | LinkedIn: https://www.linkedin.com/in/thejoelgoodman/
Arm.com
[cid:image001.png@01D395BE.02714960]
