### ISSUE TITLE
Cannot build without update_default_resources

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-edge#4]
I'm following the instructions in README, and at no point it tells me to have an `update_default_resources.c` file. But the build fails if it's not present. I don't have the UPDATE_ENABLED (or whatever it's called) macro enabled either. Could we add an empty cert to the project similar to what we do for mbed-cloud-client-example?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTGW-703

**Comment by JanneKiiskila** [comment]
This was fixed 0.5.1 release.
